- name: check your apache configuration
  hosts:  g1
  tasks:
  - block:
    - name:
      lineinfile:
       dest: /opt/apache2/conf/httpd.conf
       regexp: "^Listen 80"
       line: "Listen 8081"
       state:  present
       backup: yes
  - block:
    - name: Put some content in index.html
      copy:
        content:  "this is for ansible automation"
        dest: /opt/apache2/htdocs/index.html
        backup: yes
  - block:
    - name: Restrat the Appache2 Service
      apache2_module:
        name: rewrite
        state:  present
      notify: restart apache2
    - name: define handlers for restart apache2
      command:
        /opt/apache2/bin/apachectl start
  - block:
    - name: Check the website URL connectivity
      uri:
        url:  http://127.0.0.1:8081/
        status_code:  200
