----
- name: Get the appache and compile the system
  hosts: localhost
  tasks:
   - block:
     - name:  apache web serber
       unarchive:
        src:  http://mirrors.estointernet.in/apache//httpd/httpd-2.4.39.tar.gz
        dest: /home/ansible/
        remote_src: yes
     - name: apache util get
       unarchive:
        src:  http://mirrors.estointernet.in/apache//apr/apr-1.7.0.tar.gz
        dest: /home/ansible/
        remote_src: yes
     - name: apache apr-util get
       unarchive:
        src:  http://mirrors.estointernet.in/apache//apr/apr-util-1.6.1.tar.gz
        dest: /home/ansible/
        remote_src: yes
   - block:
     - name: create a directory
       file:
        path: /home/ansible/httpd-2.4.39/srclib/apr
        state:  directory
        mode: '0755'
     - name: create another direcory
       file:
        path:  /home/ansible/httpd-2.4.39/srclib/apr-util
        state:  directory
        mode: '0755'
   - block:
      - name: move apache apr  under httpd service
        copy:
          src: /home/ansible/apr-1.7.0/
          dest: /home/ansible/httpd-2.4.39/srclib/apr/
          remote_src: yes
      - name: move apr-util under httpd service
        copy:
          src: /home/ansible/apr-util-1.6.1/
          dest: /home/ansible/httpd-2.4.39/srclib/apr-util/
          remote_src: yes
   - block:
      - name: installing packages
        yum:
          name: gcc,make,pcre-devel,pcre,expat-devel
          state:  latest
   - block:
      - name: lets start complilation
        command:
          /home/ansible/httpd-2.4.39/configure --prefix=/opt/apache2 --with-included-apr --with-pcre
   - block:
      - name: Build the default target
        make:
          chdir: /opt/apache2
      - name: Run 'Install' target as root
        make:
          chdir:  /opt/apache2
          target: install
        register: myoutput
      - debug:
          msg:  Installtion output is {{ myoutput }}
   - block:
      - name:
        lineinfile:
          dest: /opt/apache2/conf/httpd.conf
          regexp: "^Listen 80"
          line: "Listen 8081"
          state:  present
          backup: yes
   - block:
      - name: Put some content in index.html
        copy:
          content:  "this is for ansible automation"
          dest: /opt/apache2/htdocs/index.html
          backup: yes
   - block:
      - name: Restrat the Appache2 Service
        apache2_module:
          name: rewrite
          state:  present
        notify: restart apache2
      - name: define handlers for restart apache2
        command:
          /opt/apache2/bin/apachectl start
   - block:
      - name: Check the website URL connectivity
        uri:
          url:  http://127.0.0.1:8081/
          status_code:  200
...
